# Use the SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore dependencies
COPY TaskManagementSystem.Web/*.csproj ./TaskManagementSystem.Web/
RUN dotnet restore TaskManagementSystem.Web/*.csproj

# Copy everything else and build
COPY TaskManagementSystem.Web/. ./TaskManagementSystem.Web/
RUN dotnet publish TaskManagementSystem.Web/*.csproj -c Release -o out

# Build runtime image
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/out/wwwroot .
COPY TaskManagementSystem.Web/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE $PORT
CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'