[build]
builder = "DOCKERFILE"
dockerfilePath = "TaskManagementSystem.Web/Dockerfile"

[deploy]
numReplicas = 1
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10